Add AWS SES Functionality
fondat/fondat-aws pull request #6
Opened 2021-06-01 21:39 UTC by tguo9

2021-06-02 12:59 UTC, pbryan requested changes
Requesting some changes.

2021-06-02 12:59 UTC, pbryan commented on fondat/aws/ses.py
> +            email_from: Union[str, EmailRecipient],
From and to should just be `str`. In SMTP, `MAIL FROM` and `RCPT TO` only support raw addresses, not names. If names should be included, they should be embedded in the `From` and `To` headers in the message body.

2021-06-02 12:59 UTC, pbryan commented on fondat/aws/ses.py
> +            return await client.send_email(
This should send raw.

2021-06-02 12:59 UTC, pbryan commented on fondat/aws/ses.py
> +            text_body: Template,
This type should be `str` (creating a Template should be implemented within the method). Suggest calling this `template` instead of `text_body`.

2021-06-02 12:59 UTC, pbryan commented on fondat/aws/ses.py
> +            msg = msg = message_from_string(text_body.safe_substitute(text_pram))
`msg = msg = ...` seems redundant.

2021-06-02 12:59 UTC, pbryan commented on fondat/aws/ses.py
> +            text_pram: Dict[str, str],
Maybe just call `params`? Also, can be `dict` as `typing.Dict` is deprecated.

2021-06-02 12:59 UTC, pbryan commented on fondat/aws/ses.py
> +from typing import Dict, Union
`typing.Dict` is now deprecated.

2021-06-03 00:43 UTC, tguo9 commented
Link to #7

2021-06-05 04:39 UTC, merged